# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfs.proto',
  package='gfs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tgfs.proto\x12\x03gfs\"B\n\nAddRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05peers\x18\x03 \x03(\t\x12\t\n\x01k\x18\x04 \x01(\x05\"\x16\n\x07\x43hunkId\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\"(\n\x0b\x43opyRequest\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"-\n\x0e\x43onfirmRequest\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\x12\x0e\n\x06verify\x18\x02 \x01(\x08\"\x1d\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"6\n\x0bNameRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04list\x18\x02 \x03(\t\x12\x0b\n\x03\x63\x66t\x18\x03 \x01(\x05\"\x8b\x01\n\tChunkList\x12$\n\x03map\x18\x01 \x03(\x0b\x32\x17.gfs.ChunkList.MapEntry\x12\x0e\n\x06\x63hunks\x18\x02 \x03(\t\x12\x0b\n\x03\x63\x66t\x18\x03 \x01(\x05\x1a;\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.gfs.StringList:\x02\x38\x01\"\x1a\n\nStringList\x12\x0c\n\x04strs\x18\x01 \x03(\t\"\x15\n\x06Number\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x15\n\x05\x42ytes\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x15\n\x06String\x12\x0b\n\x03str\x18\x01 \x01(\t\"\x16\n\x04\x42ool\x12\x0e\n\x06verify\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xda\x01\n\x0b\x43hunkServer\x12 \n\x04Read\x12\x0c.gfs.ChunkId\x1a\n.gfs.Bytes\x12*\n\x0b\x46irstCommit\x12\x10.gfs.CopyRequest\x1a\t.gfs.Bool\x12/\n\x0cSecondCommit\x12\x13.gfs.ConfirmRequest\x1a\n.gfs.Empty\x12\"\n\x06\x44\x65lete\x12\x0c.gfs.ChunkId\x1a\n.gfs.Empty\x12(\n\tGetChunks\x12\n.gfs.Empty\x1a\x0f.gfs.StringList2\x8c\x02\n\x0cMasterServer\x12\x30\n\x0cRegisterPeer\x12\x14.gfs.RegisterRequest\x1a\n.gfs.Empty\x12%\n\x0b\x43heckChunks\x12\n.gfs.Empty\x1a\n.gfs.Empty\x12&\n\x07GetFile\x12\x0b.gfs.String\x1a\x0e.gfs.ChunkList\x12&\n\nDeleteFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\x12(\n\x08GetPeers\x12\x0b.gfs.Number\x1a\x0f.gfs.StringList\x12)\n\tNameSpace\x12\x10.gfs.NameRequest\x1a\n.gfs.Emptyb\x06proto3'
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='gfs.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gfs.AddRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='gfs.AddRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peers', full_name='gfs.AddRequest.peers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='gfs.AddRequest.k', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=84,
)


_CHUNKID = _descriptor.Descriptor(
  name='ChunkId',
  full_name='gfs.ChunkId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='gfs.ChunkId.cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=108,
)


_COPYREQUEST = _descriptor.Descriptor(
  name='CopyRequest',
  full_name='gfs.CopyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='gfs.CopyRequest.cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='gfs.CopyRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=150,
)


_CONFIRMREQUEST = _descriptor.Descriptor(
  name='ConfirmRequest',
  full_name='gfs.ConfirmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='gfs.ConfirmRequest.cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verify', full_name='gfs.ConfirmRequest.verify', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=197,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='gfs.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='gfs.RegisterRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=228,
)


_NAMEREQUEST = _descriptor.Descriptor(
  name='NameRequest',
  full_name='gfs.NameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='gfs.NameRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list', full_name='gfs.NameRequest.list', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cft', full_name='gfs.NameRequest.cft', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=284,
)


_CHUNKLIST_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='gfs.ChunkList.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gfs.ChunkList.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='gfs.ChunkList.MapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=426,
)

_CHUNKLIST = _descriptor.Descriptor(
  name='ChunkList',
  full_name='gfs.ChunkList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map', full_name='gfs.ChunkList.map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunks', full_name='gfs.ChunkList.chunks', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cft', full_name='gfs.ChunkList.cft', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CHUNKLIST_MAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=426,
)


_STRINGLIST = _descriptor.Descriptor(
  name='StringList',
  full_name='gfs.StringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strs', full_name='gfs.StringList.strs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=454,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='gfs.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='gfs.Number.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=477,
)


_BYTES = _descriptor.Descriptor(
  name='Bytes',
  full_name='gfs.Bytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gfs.Bytes.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=500,
)


_STRING = _descriptor.Descriptor(
  name='String',
  full_name='gfs.String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='gfs.String.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=523,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='gfs.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verify', full_name='gfs.Bool.verify', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=547,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='gfs.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=556,
)

_CHUNKLIST_MAPENTRY.fields_by_name['value'].message_type = _STRINGLIST
_CHUNKLIST_MAPENTRY.containing_type = _CHUNKLIST
_CHUNKLIST.fields_by_name['map'].message_type = _CHUNKLIST_MAPENTRY
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['ChunkId'] = _CHUNKID
DESCRIPTOR.message_types_by_name['CopyRequest'] = _COPYREQUEST
DESCRIPTOR.message_types_by_name['ConfirmRequest'] = _CONFIRMREQUEST
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['NameRequest'] = _NAMEREQUEST
DESCRIPTOR.message_types_by_name['ChunkList'] = _CHUNKLIST
DESCRIPTOR.message_types_by_name['StringList'] = _STRINGLIST
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Bytes'] = _BYTES
DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

ChunkId = _reflection.GeneratedProtocolMessageType('ChunkId', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKID,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.ChunkId)
  })
_sym_db.RegisterMessage(ChunkId)

CopyRequest = _reflection.GeneratedProtocolMessageType('CopyRequest', (_message.Message,), {
  'DESCRIPTOR' : _COPYREQUEST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.CopyRequest)
  })
_sym_db.RegisterMessage(CopyRequest)

ConfirmRequest = _reflection.GeneratedProtocolMessageType('ConfirmRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMREQUEST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.ConfirmRequest)
  })
_sym_db.RegisterMessage(ConfirmRequest)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAMEREQUEST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.NameRequest)
  })
_sym_db.RegisterMessage(NameRequest)

ChunkList = _reflection.GeneratedProtocolMessageType('ChunkList', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _CHUNKLIST_MAPENTRY,
    '__module__' : 'gfs_pb2'
    # @@protoc_insertion_point(class_scope:gfs.ChunkList.MapEntry)
    })
  ,
  'DESCRIPTOR' : _CHUNKLIST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.ChunkList)
  })
_sym_db.RegisterMessage(ChunkList)
_sym_db.RegisterMessage(ChunkList.MapEntry)

StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.StringList)
  })
_sym_db.RegisterMessage(StringList)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.Number)
  })
_sym_db.RegisterMessage(Number)

Bytes = _reflection.GeneratedProtocolMessageType('Bytes', (_message.Message,), {
  'DESCRIPTOR' : _BYTES,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.Bytes)
  })
_sym_db.RegisterMessage(Bytes)

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), {
  'DESCRIPTOR' : _STRING,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.String)
  })
_sym_db.RegisterMessage(String)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.Bool)
  })
_sym_db.RegisterMessage(Bool)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.Empty)
  })
_sym_db.RegisterMessage(Empty)


_CHUNKLIST_MAPENTRY._options = None

_CHUNKSERVER = _descriptor.ServiceDescriptor(
  name='ChunkServer',
  full_name='gfs.ChunkServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=559,
  serialized_end=777,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='gfs.ChunkServer.Read',
    index=0,
    containing_service=None,
    input_type=_CHUNKID,
    output_type=_BYTES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FirstCommit',
    full_name='gfs.ChunkServer.FirstCommit',
    index=1,
    containing_service=None,
    input_type=_COPYREQUEST,
    output_type=_BOOL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SecondCommit',
    full_name='gfs.ChunkServer.SecondCommit',
    index=2,
    containing_service=None,
    input_type=_CONFIRMREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='gfs.ChunkServer.Delete',
    index=3,
    containing_service=None,
    input_type=_CHUNKID,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunks',
    full_name='gfs.ChunkServer.GetChunks',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STRINGLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHUNKSERVER)

DESCRIPTOR.services_by_name['ChunkServer'] = _CHUNKSERVER


_MASTERSERVER = _descriptor.ServiceDescriptor(
  name='MasterServer',
  full_name='gfs.MasterServer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=780,
  serialized_end=1048,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterPeer',
    full_name='gfs.MasterServer.RegisterPeer',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckChunks',
    full_name='gfs.MasterServer.CheckChunks',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='gfs.MasterServer.GetFile',
    index=2,
    containing_service=None,
    input_type=_STRING,
    output_type=_CHUNKLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFile',
    full_name='gfs.MasterServer.DeleteFile',
    index=3,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPeers',
    full_name='gfs.MasterServer.GetPeers',
    index=4,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_STRINGLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NameSpace',
    full_name='gfs.MasterServer.NameSpace',
    index=5,
    containing_service=None,
    input_type=_NAMEREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVER)

DESCRIPTOR.services_by_name['MasterServer'] = _MASTERSERVER

# @@protoc_insertion_point(module_scope)
